# Generated by Antigravity for Smithery MCP Registry
FROM node:18-alpine AS builder

WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Copy source code and config
COPY tsconfig.json ./
COPY src/ ./src/

# Build the application
RUN npm run build

# Production image
FROM node:18-alpine AS release

WORKDIR /app

# Copy package files and production dependencies only
COPY package.json package-lock.json* ./
RUN npm ci --omit=dev

# Copy compiled source
COPY --from=builder /app/dist ./dist

# Start command
CMD ["node", "dist/index.js"]
